// AUTO-GENERATED extended theme gallery (contrast-audited). Registered in theme-presets.ts.
import type { Theme } from "./types";

export const EXTRA_PRESETS: { key: string; label: string; desc: string; category: string; theme: Partial<Theme> }[] = [
  {
    "key": "teal-pro",
    "label": "Teal Pro",
    "desc": "Elevated teal for B2B commerce",
    "category": "light",
    "theme": {
      "preset": "teal-pro",
      "primary": "#0F766E",
      "brand": "#115E59",
      "accent2": "#14B8A6",
      "background": "#F8FAFC",
      "card": "#FFFFFF",
      "foreground": "#0F172A",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "dots",
      "font": "inter",
      "displayFont": "jakarta",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 62,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "ruby",
    "label": "Ruby Atelier",
    "desc": "Deep ruby, rose gold luxe",
    "category": "luxury",
    "theme": {
      "preset": "ruby",
      "primary": "#A11C33",
      "brand": "#B21E3A",
      "accent2": "#C08A7D",
      "background": "#FBF6EE",
      "card": "#FFFDF9",
      "foreground": "#2B1A1D",
      "radius": 16,
      "surface": "glass",
      "hero": "showcase",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 18,
      "opacity": 65,
      "depth": 55,
      "glow": 32,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "sage",
    "label": "Sage Ritual",
    "desc": "Calm sage and warm terracotta — quiet-luxury wellness",
    "category": "nature",
    "theme": {
      "preset": "sage",
      "primary": "#4A6152",
      "brand": "#7C4E3A",
      "accent2": "#9DB39A",
      "background": "#F4F1EA",
      "card": "#FFFFFF",
      "foreground": "#2B2F29",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "noise",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 34,
      "glow": 16,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "sandstone",
    "label": "Sandstone Atelier",
    "desc": "Sun-baked terracotta and warm sand — an editorial luxury palette",
    "category": "luxury",
    "theme": {
      "preset": "sandstone",
      "primary": "#B04A2C",
      "brand": "#A03C22",
      "accent2": "#E39B54",
      "background": "#F6EEE1",
      "card": "#FFFAF3",
      "foreground": "#33261C",
      "radius": 18,
      "surface": "neo",
      "hero": "split",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 24,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "lavender-fields",
    "label": "Lavender Fields",
    "desc": "Soft violet beauty in bloom",
    "category": "glass",
    "theme": {
      "preset": "lavender-fields",
      "primary": "#6D45B8",
      "brand": "#9B3FB5",
      "accent2": "#C7A4F0",
      "background": "#F6F4FC",
      "card": "#FDFCFF",
      "foreground": "#2E2547",
      "radius": 20,
      "surface": "glass",
      "hero": "split",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 18,
      "opacity": 65,
      "depth": 35,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "indigo-night",
    "label": "Indigo Night",
    "desc": "Deep indigo and cyan aurora glass with luminous accents",
    "category": "glass",
    "theme": {
      "preset": "indigo-night",
      "primary": "#4F46E5",
      "brand": "#0A7C9C",
      "accent2": "#22D3EE",
      "background": "#0A0B1E",
      "card": "#14162E",
      "foreground": "#E9ECFB",
      "radius": 16,
      "surface": "glass",
      "hero": "gradient",
      "bg": "aurora",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 55,
      "glow": 68,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "honey",
    "label": "Golden Honey",
    "desc": "Warm golden artisan glow with espresso ink on cream",
    "category": "luxury",
    "theme": {
      "preset": "honey",
      "primary": "#B45309",
      "brand": "#92400E",
      "accent2": "#F59E0B",
      "background": "#FDF4E3",
      "card": "#FFFBF3",
      "foreground": "#3A281A",
      "radius": 20,
      "surface": "neo",
      "hero": "spotlight",
      "bg": "gradient",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "charcoal-gold",
    "label": "Onyx & Gold",
    "desc": "Tailored luxury in charcoal and gold",
    "category": "luxury",
    "theme": {
      "preset": "charcoal-gold",
      "primary": "#8A6B2C",
      "brand": "#9C661F",
      "accent2": "#E6C15C",
      "background": "#14110D",
      "card": "#1D1913",
      "foreground": "#F3ECDD",
      "radius": 8,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "noise",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 60,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "ocean-deep",
    "label": "Abyssal Tide",
    "desc": "Immersive deep-sea aqua glow",
    "category": "dark",
    "theme": {
      "preset": "ocean-deep",
      "primary": "#0E7490",
      "brand": "#1E5AA8",
      "accent2": "#22D3EE",
      "background": "#07182A",
      "card": "#0E2438",
      "foreground": "#E6F4F9",
      "radius": 18,
      "surface": "aurora",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 65,
      "glow": 74,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "blossom",
    "label": "Cherry Blossom",
    "desc": "Delicate petals, frosted glass",
    "category": "glass",
    "theme": {
      "preset": "blossom",
      "primary": "#C13A66",
      "brand": "#A82F57",
      "accent2": "#FFAECB",
      "background": "#FFF5F8",
      "card": "#FFFFFF",
      "foreground": "#3A2A33",
      "radius": 18,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 18,
      "opacity": 68,
      "depth": 30,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "slate-dark",
    "label": "Slate Nimbus",
    "desc": "Refined slate glass with a soft azure-and-indigo glow",
    "category": "dark",
    "theme": {
      "preset": "slate-dark",
      "primary": "#2F6BE0",
      "brand": "#0F79BE",
      "accent2": "#6366F1",
      "background": "#0B1120",
      "card": "#141C2E",
      "foreground": "#E8EEFA",
      "radius": 14,
      "surface": "glass",
      "hero": "diagonal",
      "bg": "noise",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 18,
      "opacity": 66,
      "depth": 55,
      "glow": 55,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "mocha",
    "label": "Mocha Cream",
    "desc": "Cozy coffee and cream warmth",
    "category": "luxury",
    "theme": {
      "preset": "mocha",
      "primary": "#6F4E37",
      "brand": "#A05A2C",
      "accent2": "#D9A05B",
      "background": "#F3EADD",
      "card": "#FAF4EA",
      "foreground": "#3A2A1E",
      "radius": 18,
      "surface": "neo",
      "hero": "split",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 65,
      "glow": 25,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "midnight-rose",
    "label": "Midnight Rose",
    "desc": "Neon Rose After Dark",
    "category": "dark",
    "theme": {
      "preset": "midnight-rose",
      "primary": "#DB2777",
      "brand": "#E11D63",
      "accent2": "#FF6AA8",
      "background": "#16121A",
      "card": "#211B29",
      "foreground": "#F6EDF2",
      "radius": 18,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "jakarta",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 70,
      "glow": 72,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "forest-dark",
    "label": "Verdant Noir",
    "desc": "Deep forest glass with a bright lime glow",
    "category": "nature",
    "theme": {
      "preset": "forest-dark",
      "primary": "#15803D",
      "brand": "#4D7C0F",
      "accent2": "#BEF264",
      "background": "#0A140E",
      "card": "#122A1D",
      "foreground": "#E9F4ED",
      "radius": 20,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "manrope",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 18,
      "opacity": 68,
      "depth": 55,
      "glow": 60,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "steel",
    "label": "Steel Voltage",
    "desc": "Industrial steel meets electric current — deep blue-black ground with vivid voltage-blue accents.",
    "category": "dark",
    "theme": {
      "preset": "steel",
      "primary": "#2563EB",
      "brand": "#1A63D6",
      "accent2": "#38BDF8",
      "background": "#0C0F16",
      "card": "#11151D",
      "foreground": "#E7ECF3",
      "radius": 8,
      "surface": "outline",
      "hero": "spotlight",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 20,
      "glow": 60,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "olive",
    "label": "Olive Harvest",
    "desc": "Sun-warmed olive, mustard, and gold on warm cream",
    "category": "nature",
    "theme": {
      "preset": "olive",
      "primary": "#4C5A2E",
      "brand": "#986C10",
      "accent2": "#C9A227",
      "background": "#F7F3E9",
      "card": "#FBF8F0",
      "foreground": "#2B2A22",
      "radius": 18,
      "surface": "neo",
      "hero": "split",
      "bg": "mesh",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "terracotta",
    "label": "Terracotta Clay",
    "desc": "Handcrafted clay warmth with an artisan glow",
    "category": "nature",
    "theme": {
      "preset": "terracotta",
      "primary": "#BC5136",
      "brand": "#C0492B",
      "accent2": "#E0A15E",
      "background": "#FBF4EC",
      "card": "#FFFBF6",
      "foreground": "#33251C",
      "radius": 18,
      "surface": "neo",
      "hero": "split",
      "bg": "mesh",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "gold-lux",
    "label": "Gilded Atelier",
    "desc": "Cream and gilded high-jewellery luxury",
    "category": "luxury",
    "theme": {
      "preset": "gold-lux",
      "primary": "#8C6A24",
      "brand": "#93691C",
      "accent2": "#D8B35A",
      "background": "#FAF5EC",
      "card": "#FFFDF8",
      "foreground": "#2B2118",
      "radius": 14,
      "surface": "glass",
      "hero": "showcase",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 18,
      "opacity": 68,
      "depth": 52,
      "glow": 34,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "cobalt",
    "label": "Cobalt Corporate",
    "desc": "Bold cobalt, crisp corporate SaaS",
    "category": "light",
    "theme": {
      "preset": "cobalt",
      "primary": "#1A4FE0",
      "brand": "#0B3FD4",
      "accent2": "#4C8CFF",
      "background": "#F5F8FD",
      "card": "#FFFFFF",
      "foreground": "#0C1526",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "jakarta",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 65,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "citrus",
    "label": "Citrus Squeeze",
    "desc": "Fresh-squeezed citrus energy — blood orange, lime zest, and lemon",
    "category": "playful",
    "theme": {
      "preset": "citrus",
      "primary": "#CE4300",
      "brand": "#4D7C0F",
      "accent2": "#FFC400",
      "background": "#FFF5E4",
      "card": "#FFFFFF",
      "foreground": "#2A1E12",
      "radius": 22,
      "surface": "clay",
      "hero": "showcase",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "peach",
    "label": "Peach Sorbet",
    "desc": "Soft coral, cute lifestyle",
    "category": "playful",
    "theme": {
      "preset": "peach",
      "primary": "#CE3826",
      "brand": "#CC3349",
      "accent2": "#FF8A5E",
      "background": "#FFF3EB",
      "card": "#FFFBF7",
      "foreground": "#3A2A24",
      "radius": 22,
      "surface": "clay",
      "hero": "split",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 22,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "arctic",
    "label": "Arctic Frost",
    "desc": "Icy blue premium electronics",
    "category": "minimal",
    "theme": {
      "preset": "arctic",
      "primary": "#0B6BCB",
      "brand": "#0546A0",
      "accent2": "#5CC6F5",
      "background": "#F4F9FC",
      "card": "#FFFFFF",
      "foreground": "#10212E",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 22,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "plum",
    "label": "Velvet Plum",
    "desc": "Gilded plum with luminous glass and antique-gold accents",
    "category": "luxury",
    "theme": {
      "preset": "plum",
      "primary": "#8B41B4",
      "brand": "#9A6B12",
      "accent2": "#E4B85E",
      "background": "#180B22",
      "card": "#241435",
      "foreground": "#F5EAF7",
      "radius": 18,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 45,
      "glow": 55,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "aqua-marine",
    "label": "Aquamarine Coast",
    "desc": "Fresh coastal glass in turquoise and aqua-mint",
    "category": "glass",
    "theme": {
      "preset": "aqua-marine",
      "primary": "#0A7480",
      "brand": "#0E7490",
      "accent2": "#2DD4C0",
      "background": "#EAF8F8",
      "card": "#FFFFFF",
      "foreground": "#062C31",
      "radius": 20,
      "surface": "glass",
      "hero": "split",
      "bg": "waves",
      "font": "manrope",
      "displayFont": "jakarta",
      "fontScale": 1,
      "blur": 18,
      "opacity": 68,
      "depth": 45,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "berry",
    "label": "Berry Bloom",
    "desc": "Vibrant berry, playfully bold",
    "category": "playful",
    "theme": {
      "preset": "berry",
      "primary": "#C41E6F",
      "brand": "#7A1FB0",
      "accent2": "#9B30D9",
      "background": "#FFF5FB",
      "card": "#FFFFFF",
      "foreground": "#2A1A2E",
      "radius": 20,
      "surface": "clay",
      "hero": "showcase",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "spring-meadow",
    "label": "Spring Meadow",
    "desc": "Sunlit greens with a cheerful buttercup bloom",
    "category": "nature",
    "theme": {
      "preset": "spring-meadow",
      "primary": "#0C8038",
      "brand": "#0B7A46",
      "accent2": "#F7CE3B",
      "background": "#F1FAF0",
      "card": "#FFFFFF",
      "foreground": "#123528",
      "radius": 18,
      "surface": "neo",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "manrope",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 30,
      "dark": false,
      "gradientButtons": false,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "denim",
    "label": "Denim & Tan",
    "desc": "Casual denim blue with warm leather and tan tones",
    "category": "light",
    "theme": {
      "preset": "denim",
      "primary": "#35618E",
      "brand": "#8C5E34",
      "accent2": "#C8A87A",
      "background": "#FAF7F2",
      "card": "#FFFFFF",
      "foreground": "#22303F",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 58,
      "glow": 24,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "carbon",
    "label": "Carbon Circuit",
    "desc": "Electric neon on pure carbon",
    "category": "dark",
    "theme": {
      "preset": "carbon",
      "primary": "#0A7A3A",
      "brand": "#0A7A42",
      "accent2": "#33FF8C",
      "background": "#070A08",
      "card": "#0E1411",
      "foreground": "#E9F1EC",
      "radius": 14,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 78,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "sunrise",
    "label": "Sunrise Bloom",
    "desc": "Warm optimistic morning light",
    "category": "vibrant",
    "theme": {
      "preset": "sunrise",
      "primary": "#C3341F",
      "brand": "#C81E5B",
      "accent2": "#FF6AA2",
      "background": "#FFF4EC",
      "card": "#FFFFFF",
      "foreground": "#2E1A17",
      "radius": 20,
      "surface": "glass",
      "hero": "gradient",
      "bg": "gradient",
      "font": "inter",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 18,
      "opacity": 70,
      "depth": 55,
      "glow": 34,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "crimson",
    "label": "Crimson Velocity",
    "desc": "High-energy glossy crimson streetwear with spotlight hero and ray-lit dark backdrop",
    "category": "vibrant",
    "theme": {
      "preset": "crimson",
      "primary": "#E11D31",
      "brand": "#E5122F",
      "accent2": "#FF2E45",
      "background": "#0A0A0C",
      "card": "#151519",
      "foreground": "#F4F4F6",
      "radius": 12,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "rays",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1.03,
      "blur": 0,
      "opacity": 100,
      "depth": 72,
      "glow": 72,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "brutalist-mono",
    "label": "Brutalist Mono",
    "desc": "Raw high-contrast editorial brutalism",
    "category": "minimal",
    "theme": {
      "preset": "brutalist-mono",
      "primary": "#000000",
      "brand": "#000000",
      "accent2": "#FF3D00",
      "background": "#FFFFFF",
      "card": "#FFFFFF",
      "foreground": "#000000",
      "radius": 0,
      "surface": "outline",
      "hero": "split",
      "bg": "solid",
      "font": "space",
      "displayFont": "space",
      "fontScale": 1.1,
      "blur": 0,
      "opacity": 100,
      "depth": 0,
      "glow": 0,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "paper-craft",
    "label": "Paper Craft",
    "desc": "Tactile stationery for artisan makers",
    "category": "minimal",
    "theme": {
      "preset": "paper-craft",
      "primary": "#5C5347",
      "brand": "#7A6A55",
      "accent2": "#9C876C",
      "background": "#F5F1E9",
      "card": "#FBF8F2",
      "foreground": "#33302A",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "noise",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 0,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "vaporwave-dream",
    "label": "Vaporwave Dream",
    "desc": "Neon 80s glow, gradient dreams",
    "category": "vibrant",
    "theme": {
      "preset": "vaporwave-dream",
      "primary": "#CC1D8F",
      "brand": "#8B2FE8",
      "accent2": "#2DE2E6",
      "background": "#100A24",
      "card": "#1A1140",
      "foreground": "#F5E9FF",
      "radius": 16,
      "surface": "aurora",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "jakarta",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 60,
      "glow": 75,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "autumn-harvest",
    "label": "Autumn Harvest",
    "desc": "Amber, rust, and cozy warmth",
    "category": "nature",
    "theme": {
      "preset": "autumn-harvest",
      "primary": "#C2410C",
      "brand": "#9A3412",
      "accent2": "#D97706",
      "background": "#FDF6EC",
      "card": "#FFFFFF",
      "foreground": "#2E1C10",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "inter",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 15,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "porcelain-blue",
    "label": "Porcelain Blue",
    "desc": "Delicate willow blue, editorial calm",
    "category": "minimal",
    "theme": {
      "preset": "porcelain-blue",
      "primary": "#3D6A85",
      "brand": "#2E5468",
      "accent2": "#7FA8BF",
      "background": "#F6F8FA",
      "card": "#FFFFFF",
      "foreground": "#1E2A33",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "solid",
      "font": "inter",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 30,
      "glow": 8,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "zen-stone",
    "label": "Zen Stone",
    "desc": "Muted taupe, mindful calm",
    "category": "minimal",
    "theme": {
      "preset": "zen-stone",
      "primary": "#5C6570",
      "brand": "#6F6456",
      "accent2": "#9C8E7B",
      "background": "#F1EFEA",
      "card": "#FBFAF8",
      "foreground": "#33373D",
      "radius": 16,
      "surface": "elevated",
      "hero": "minimal",
      "bg": "solid",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 24,
      "glow": 0,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "safari-earth",
    "label": "Safari Earth",
    "desc": "Rugged warmth for the wild",
    "category": "nature",
    "theme": {
      "preset": "safari-earth",
      "primary": "#B84E1C",
      "brand": "#6E5F3B",
      "accent2": "#D4A867",
      "background": "#FAF6EF",
      "card": "#FFFCF6",
      "foreground": "#2A2118",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 8,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "matcha-cafe",
    "label": "Matcha Cream",
    "desc": "Calm organic wellness in cream",
    "category": "nature",
    "theme": {
      "preset": "matcha-cafe",
      "primary": "#557043",
      "brand": "#46603A",
      "accent2": "#AD6340",
      "background": "#F6F4EB",
      "card": "#FDFCF6",
      "foreground": "#2A3627",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 0,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "onyx-luxe",
    "label": "Onyx Luxe",
    "desc": "Platinum shine on deep onyx",
    "category": "luxury",
    "theme": {
      "preset": "onyx-luxe",
      "primary": "#4C4C57",
      "brand": "#63636F",
      "accent2": "#C9CBD2",
      "background": "#09090B",
      "card": "#141418",
      "foreground": "#ECECF1",
      "radius": 8,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 40,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "desert-bloom",
    "label": "Desert Bloom",
    "desc": "Dusty rose meets cactus green",
    "category": "nature",
    "theme": {
      "preset": "desert-bloom",
      "primary": "#AC5F55",
      "brand": "#9E564E",
      "accent2": "#6B7955",
      "background": "#F7F0E5",
      "card": "#FFFBF4",
      "foreground": "#3B2E27",
      "radius": 18,
      "surface": "clay",
      "hero": "showcase",
      "bg": "noise",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 30,
      "glow": 8,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "tech-slate",
    "label": "Cobalt Slate",
    "desc": "Crisp cool-blue corporate clarity",
    "category": "minimal",
    "theme": {
      "preset": "tech-slate",
      "primary": "#2563EB",
      "brand": "#1D4ED8",
      "accent2": "#0EA5E9",
      "background": "#F6F8FB",
      "card": "#FFFFFF",
      "foreground": "#0F172A",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "velvet-noir",
    "label": "Velvet Noir",
    "desc": "Moody burgundy velvet luxury",
    "category": "luxury",
    "theme": {
      "preset": "velvet-noir",
      "primary": "#A01D42",
      "brand": "#7E1C39",
      "accent2": "#C6A15C",
      "background": "#130A0D",
      "card": "#211217",
      "foreground": "#F4E8E3",
      "radius": 16,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 50,
      "glow": 40,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "electric-violet",
    "label": "Electric Violet",
    "desc": "Radiant violet beauty tech",
    "category": "vibrant",
    "theme": {
      "preset": "electric-violet",
      "primary": "#7C3AED",
      "brand": "#6D28D9",
      "accent2": "#DB2777",
      "background": "#FAF8FF",
      "card": "#FFFFFF",
      "foreground": "#1E1B2E",
      "radius": 18,
      "surface": "elevated",
      "hero": "gradient",
      "bg": "solid",
      "font": "inter",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 30,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "moss-glen",
    "label": "Moss Glen",
    "desc": "Deep forest meets bark earth",
    "category": "nature",
    "theme": {
      "preset": "moss-glen",
      "primary": "#2E6B45",
      "brand": "#35774A",
      "accent2": "#7A5A3C",
      "background": "#F5F3EA",
      "card": "#FBFAF4",
      "foreground": "#1F2A21",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "noise",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 0,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "candy-pop",
    "label": "Candy Pop",
    "desc": "Bright glossy sugar-rush palette",
    "category": "playful",
    "theme": {
      "preset": "candy-pop",
      "primary": "#D81B60",
      "brand": "#7C3AED",
      "accent2": "#00BCD4",
      "background": "#FFF6FB",
      "card": "#FFFFFF",
      "foreground": "#2B1533",
      "radius": 24,
      "surface": "glossy",
      "hero": "showcase",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "tropical-punch",
    "label": "Tropical Punch",
    "desc": "Sun-soaked summer beachwear punch",
    "category": "vibrant",
    "theme": {
      "preset": "tropical-punch",
      "primary": "#D6156B",
      "brand": "#BC4409",
      "accent2": "#A6E22E",
      "background": "#FFF6EC",
      "card": "#FFFFFF",
      "foreground": "#2E1A12",
      "radius": 22,
      "surface": "clay",
      "hero": "showcase",
      "bg": "rays",
      "font": "inter",
      "displayFont": "poppins",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 24,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "papyrus-editorial",
    "label": "Papyrus Press",
    "desc": "Aged paper, ink-black serifs",
    "category": "light",
    "theme": {
      "preset": "papyrus-editorial",
      "primary": "#2B2620",
      "brand": "#7C2D2A",
      "accent2": "#A8834E",
      "background": "#F4EDDC",
      "card": "#FCF8EF",
      "foreground": "#211D17",
      "radius": 4,
      "surface": "elevated",
      "hero": "split",
      "bg": "noise",
      "font": "playfair",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 20,
      "glow": 0,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "linen-white",
    "label": "Linen White",
    "desc": "Airy warm linen minimalism",
    "category": "minimal",
    "theme": {
      "preset": "linen-white",
      "primary": "#7C6A50",
      "brand": "#83694C",
      "accent2": "#A68A64",
      "background": "#F6F1E9",
      "card": "#FCF9F3",
      "foreground": "#322E27",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "solid",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 18,
      "glow": 0,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "cocoa-cream",
    "label": "Cocoa Cream",
    "desc": "Rich cocoa, soft cream warmth",
    "category": "luxury",
    "theme": {
      "preset": "cocoa-cream",
      "primary": "#6B4226",
      "brand": "#5C3A24",
      "accent2": "#C0854E",
      "background": "#FBF4EA",
      "card": "#FFFCF7",
      "foreground": "#3A2317",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "solid",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 14,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "mint-frost",
    "label": "Mint Frost",
    "desc": "Fresh pale mint, clean white",
    "category": "nature",
    "theme": {
      "preset": "mint-frost",
      "primary": "#0A8360",
      "brand": "#0B7A66",
      "accent2": "#6FD6BC",
      "background": "#F1FAF6",
      "card": "#FFFFFF",
      "foreground": "#123A34",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "ink-noir",
    "label": "Ink Noir",
    "desc": "Stark black-and-white designer noir",
    "category": "dark",
    "theme": {
      "preset": "ink-noir",
      "primary": "#1F1F1F",
      "brand": "#333333",
      "accent2": "#DEDEDE",
      "background": "#0A0A0A",
      "card": "#171717",
      "foreground": "#FFFFFF",
      "radius": 2,
      "surface": "elevated",
      "hero": "fullbleed",
      "bg": "noise",
      "font": "inter",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 55,
      "glow": 10,
      "dark": true,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "flamingo-tropic",
    "label": "Flamingo Tropic",
    "desc": "Bright flamingo-and-turquoise beach glam",
    "category": "playful",
    "theme": {
      "preset": "flamingo-tropic",
      "primary": "#D8306D",
      "brand": "#0C8080",
      "accent2": "#1ED4C9",
      "background": "#FFF5F8",
      "card": "#FFFFFF",
      "foreground": "#17323B",
      "radius": 20,
      "surface": "glossy",
      "hero": "showcase",
      "bg": "waves",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 55,
      "glow": 28,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "fern-hollow",
    "label": "Fern Hollow",
    "desc": "Grounded green for growing things",
    "category": "nature",
    "theme": {
      "preset": "fern-hollow",
      "primary": "#3E6B4A",
      "brand": "#2E5539",
      "accent2": "#96694A",
      "background": "#F4F1E8",
      "card": "#FCFAF3",
      "foreground": "#232B22",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "noise",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 12,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "iris-bloom",
    "label": "Iris Bloom",
    "desc": "Delicate iris purple for florists",
    "category": "nature",
    "theme": {
      "preset": "iris-bloom",
      "primary": "#6D28D9",
      "brand": "#7C3AED",
      "accent2": "#43A047",
      "background": "#FAF7FD",
      "card": "#FFFFFF",
      "foreground": "#2A1F3D",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 15,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "chartreuse-punch",
    "label": "Chartreuse Punch",
    "desc": "Electric lime, maximum energy",
    "category": "vibrant",
    "theme": {
      "preset": "chartreuse-punch",
      "primary": "#3F6212",
      "brand": "#16180E",
      "accent2": "#C7F001",
      "background": "#FAFCF4",
      "card": "#FFFFFF",
      "foreground": "#12160A",
      "radius": 14,
      "surface": "elevated",
      "hero": "diagonal",
      "bg": "grid",
      "font": "manrope",
      "displayFont": "space",
      "fontScale": 1.03,
      "blur": 0,
      "opacity": 100,
      "depth": 55,
      "glow": 34,
      "dark": false,
      "gradientButtons": false,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "pearl-atelier",
    "label": "Pearl Atelier",
    "desc": "Luminous pearl, refined silver luxury",
    "category": "luxury",
    "theme": {
      "preset": "pearl-atelier",
      "primary": "#6C7078",
      "brand": "#383B41",
      "accent2": "#B8BCC2",
      "background": "#F7F5F0",
      "card": "#FFFFFF",
      "foreground": "#23252A",
      "radius": 8,
      "surface": "elevated",
      "hero": "centered",
      "bg": "solid",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 28,
      "glow": 12,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "asphalt-lime",
    "label": "Asphalt Volt",
    "desc": "Aggressive dark for peak performance",
    "category": "dark",
    "theme": {
      "preset": "asphalt-lime",
      "primary": "#4E6E14",
      "brand": "#3A5310",
      "accent2": "#C7F63E",
      "background": "#0A0B0C",
      "card": "#15171B",
      "foreground": "#F4F6F3",
      "radius": 6,
      "surface": "elevated",
      "hero": "diagonal",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 75,
      "glow": 70,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "golden-sahara",
    "label": "Golden Sahara",
    "desc": "Sunbaked sand and rust",
    "category": "luxury",
    "theme": {
      "preset": "golden-sahara",
      "primary": "#A85C1A",
      "brand": "#A75F1D",
      "accent2": "#B23A20",
      "background": "#FAF1DE",
      "card": "#FFFBF3",
      "foreground": "#3A2617",
      "radius": 14,
      "surface": "clay",
      "hero": "showcase",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "cloud-nine",
    "label": "Cloud Nine",
    "desc": "Restful cloud grey serenity",
    "category": "minimal",
    "theme": {
      "preset": "cloud-nine",
      "primary": "#5B6B7F",
      "brand": "#4E5D70",
      "accent2": "#9AA0C4",
      "background": "#F6F7F9",
      "card": "#FFFFFF",
      "foreground": "#2B3440",
      "radius": 18,
      "surface": "elevated",
      "hero": "centered",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "manrope",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 8,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "frost-pine",
    "label": "Frost Pine",
    "desc": "Festive frosted pine and silver",
    "category": "nature",
    "theme": {
      "preset": "frost-pine",
      "primary": "#0F6B4C",
      "brand": "#0C5540",
      "accent2": "#7EA8AE",
      "background": "#EEF5F1",
      "card": "#FFFFFF",
      "foreground": "#0B2E24",
      "radius": 16,
      "surface": "glass",
      "hero": "showcase",
      "bg": "mesh",
      "font": "inter",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 18,
      "opacity": 66,
      "depth": 40,
      "glow": 24,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "jade-imperial",
    "label": "Jade Imperial",
    "desc": "Deep jade, antique imperial gold",
    "category": "luxury",
    "theme": {
      "preset": "jade-imperial",
      "primary": "#0F7A54",
      "brand": "#0C6A48",
      "accent2": "#C9A24B",
      "background": "#08130F",
      "card": "#11211B",
      "foreground": "#F3E8CE",
      "radius": 8,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 50,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "saffron-market",
    "label": "Saffron Bazaar",
    "desc": "Warm spice and textile hues",
    "category": "vibrant",
    "theme": {
      "preset": "saffron-market",
      "primary": "#C2410C",
      "brand": "#B91C1C",
      "accent2": "#F59E0B",
      "background": "#FFF7ED",
      "card": "#FFFFFF",
      "foreground": "#431407",
      "radius": 16,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 24,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "copper-patina",
    "label": "Copper Patina",
    "desc": "Oxidized copper, teal verdigris",
    "category": "dark",
    "theme": {
      "preset": "copper-patina",
      "primary": "#A85A2E",
      "brand": "#9E5430",
      "accent2": "#4FA896",
      "background": "#17110D",
      "card": "#241A12",
      "foreground": "#F2E6D8",
      "radius": 8,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 62,
      "glow": 32,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "wheatfield",
    "label": "Wheatfield",
    "desc": "Sunlit wheat gold, soft sky",
    "category": "nature",
    "theme": {
      "preset": "wheatfield",
      "primary": "#9C6410",
      "brand": "#8F5A0E",
      "accent2": "#5EA0D8",
      "background": "#FBF5E9",
      "card": "#FFFDF7",
      "foreground": "#362B18",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 24,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "harvest-gold",
    "label": "Harvest Gold",
    "desc": "Warm 70s earthy nostalgia",
    "category": "nature",
    "theme": {
      "preset": "harvest-gold",
      "primary": "#9E5F16",
      "brand": "#587523",
      "accent2": "#8A4E22",
      "background": "#F7ECD5",
      "card": "#FFF7E6",
      "foreground": "#3A2A12",
      "radius": 14,
      "surface": "clay",
      "hero": "split",
      "bg": "dots",
      "font": "inter",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 10,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "espresso-noir",
    "label": "Espresso Noir",
    "desc": "Intimate espresso with gold flecks",
    "category": "luxury",
    "theme": {
      "preset": "espresso-noir",
      "primary": "#96633A",
      "brand": "#8F5D34",
      "accent2": "#DDA94D",
      "background": "#17100B",
      "card": "#221811",
      "foreground": "#F2E6D6",
      "radius": 14,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 65,
      "glow": 55,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "sky-canvas",
    "label": "Sky Canvas",
    "desc": "Crisp sky blue on white",
    "category": "minimal",
    "theme": {
      "preset": "sky-canvas",
      "primary": "#0077C2",
      "brand": "#0369A1",
      "accent2": "#38BDF8",
      "background": "#F7FAFD",
      "card": "#FFFFFF",
      "foreground": "#0F172A",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "inter",
      "displayFont": "jakarta",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 22,
      "glow": 8,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "abyss-teal",
    "label": "Abyss Teal",
    "desc": "Immersive depths, bright cyan glow",
    "category": "dark",
    "theme": {
      "preset": "abyss-teal",
      "primary": "#0A7A8C",
      "brand": "#0A6E8A",
      "accent2": "#2EEFDE",
      "background": "#04171B",
      "card": "#0A2830",
      "foreground": "#E8FCFB",
      "radius": 14,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 66,
      "depth": 60,
      "glow": 70,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "slate-mint",
    "label": "Slate Mint",
    "desc": "Trustworthy slate with mint clarity",
    "category": "light",
    "theme": {
      "preset": "slate-mint",
      "primary": "#33475B",
      "brand": "#145E54",
      "accent2": "#2FD6A6",
      "background": "#F4F7F9",
      "card": "#FFFFFF",
      "foreground": "#0F1B2A",
      "radius": 12,
      "surface": "elevated",
      "hero": "split",
      "bg": "grid",
      "font": "inter",
      "displayFont": "manrope",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 12,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "lilac-mist",
    "label": "Lilac Mist",
    "desc": "Soft lilac spa serenity",
    "category": "minimal",
    "theme": {
      "preset": "lilac-mist",
      "primary": "#7B5EC0",
      "brand": "#6E52B3",
      "accent2": "#8E9BD4",
      "background": "#F4F2F9",
      "card": "#FCFBFE",
      "foreground": "#3A3350",
      "radius": 18,
      "surface": "elevated",
      "hero": "split",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 15,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "blush-suede",
    "label": "Blush Suede",
    "desc": "Pastel rose, warm suede luxe",
    "category": "luxury",
    "theme": {
      "preset": "blush-suede",
      "primary": "#A85D67",
      "brand": "#8E5560",
      "accent2": "#C2A08A",
      "background": "#F7EFE9",
      "card": "#FDF8F4",
      "foreground": "#40302E",
      "radius": 18,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 42,
      "glow": 15,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "gunmetal-flux",
    "label": "Gunmetal Flux",
    "desc": "Electric blue on gunmetal steel",
    "category": "dark",
    "theme": {
      "preset": "gunmetal-flux",
      "primary": "#2668E0",
      "brand": "#2264D8",
      "accent2": "#38BDF8",
      "background": "#14181F",
      "card": "#1C222B",
      "foreground": "#E8EDF3",
      "radius": 14,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 62,
      "glow": 52,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "seafoam-breeze",
    "label": "Seafoam Breeze",
    "desc": "Breezy coastal seafoam and sand",
    "category": "nature",
    "theme": {
      "preset": "seafoam-breeze",
      "primary": "#0B7A6F",
      "brand": "#0A7D72",
      "accent2": "#F0956A",
      "background": "#F6F2E9",
      "card": "#FFFFFF",
      "foreground": "#103B38",
      "radius": 16,
      "surface": "elevated",
      "hero": "split",
      "bg": "waves",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 40,
      "glow": 8,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "glacier-blue",
    "label": "Glacier Blue",
    "desc": "Crisp glacial blue, pristine white",
    "category": "light",
    "theme": {
      "preset": "glacier-blue",
      "primary": "#0B74A8",
      "brand": "#0E6CA6",
      "accent2": "#37B7D6",
      "background": "#F5F9FC",
      "card": "#FFFFFF",
      "foreground": "#102A38",
      "radius": 14,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "rosewood-lux",
    "label": "Rosewood Lux",
    "desc": "Polished brass, rich rosewood dark",
    "category": "luxury",
    "theme": {
      "preset": "rosewood-lux",
      "primary": "#9B4A3A",
      "brand": "#8A4030",
      "accent2": "#C9A24E",
      "background": "#1A120F",
      "card": "#251A15",
      "foreground": "#F3E7D8",
      "radius": 10,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 52,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "pistachio-soft",
    "label": "Pistachio Cream",
    "desc": "Sweet pastel pistachio and cream",
    "category": "playful",
    "theme": {
      "preset": "pistachio-soft",
      "primary": "#557E3C",
      "brand": "#47702F",
      "accent2": "#CE6079",
      "background": "#FAF6EA",
      "card": "#FFFDF8",
      "foreground": "#33402A",
      "radius": 20,
      "surface": "elevated",
      "hero": "split",
      "bg": "gradient",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 38,
      "glow": 10,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "periwinkle-dream",
    "label": "Periwinkle Dream",
    "desc": "Dreamy pastel periwinkle and lilac",
    "category": "light",
    "theme": {
      "preset": "periwinkle-dream",
      "primary": "#5B5ECB",
      "brand": "#665BCF",
      "accent2": "#9868D2",
      "background": "#F5F4FD",
      "card": "#FFFFFF",
      "foreground": "#2C2C4C",
      "radius": 18,
      "surface": "elevated",
      "hero": "centered",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "monsoon-teal",
    "label": "Monsoon Teal",
    "desc": "Muted teal for monsoon rainwear",
    "category": "dark",
    "theme": {
      "preset": "monsoon-teal",
      "primary": "#0E7C74",
      "brand": "#0B7C8A",
      "accent2": "#52697A",
      "background": "#101C20",
      "card": "#16262B",
      "foreground": "#E4EDEF",
      "radius": 16,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "manrope",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 45,
      "glow": 55,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "amethyst-glow",
    "label": "Amethyst Aura",
    "desc": "Serene neon amethyst aura",
    "category": "dark",
    "theme": {
      "preset": "amethyst-glow",
      "primary": "#8B47E0",
      "brand": "#7E3FF2",
      "accent2": "#C77DFF",
      "background": "#0F0A1C",
      "card": "#1A1030",
      "foreground": "#F1EBFF",
      "radius": 20,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 20,
      "opacity": 65,
      "depth": 60,
      "glow": 62,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "burnt-sienna",
    "label": "Sienna Clay",
    "desc": "Earthen warmth for handmade ceramics",
    "category": "nature",
    "theme": {
      "preset": "burnt-sienna",
      "primary": "#A94B34",
      "brand": "#8C3A24",
      "accent2": "#C58A3D",
      "background": "#F8F0E3",
      "card": "#FEFBF5",
      "foreground": "#2E2119",
      "radius": 16,
      "surface": "clay",
      "hero": "split",
      "bg": "noise",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 35,
      "glow": 8,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "marigold-fest",
    "label": "Marigold Fest",
    "desc": "Festive marigold meets vivid magenta",
    "category": "vibrant",
    "theme": {
      "preset": "marigold-fest",
      "primary": "#C81D77",
      "brand": "#A85F00",
      "accent2": "#F5A623",
      "background": "#FFF6E6",
      "card": "#FFFFFF",
      "foreground": "#3D1420",
      "radius": 16,
      "surface": "elevated",
      "hero": "showcase",
      "bg": "mesh",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 28,
      "dark": false,
      "gradientButtons": false,
      "hover3d": false,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "titanium-rose",
    "label": "Titanium Rose",
    "desc": "Brushed titanium meets rose gold",
    "category": "luxury",
    "theme": {
      "preset": "titanium-rose",
      "primary": "#A35A67",
      "brand": "#A05A66",
      "accent2": "#6C737C",
      "background": "#F1F2F4",
      "card": "#FFFFFF",
      "foreground": "#2A2D33",
      "radius": 12,
      "surface": "elevated",
      "hero": "showcase",
      "bg": "gradient",
      "font": "manrope",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 18,
      "dark": false,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "canopy-green",
    "label": "Amber Canopy",
    "desc": "Lush canopy dark, amber light",
    "category": "nature",
    "theme": {
      "preset": "canopy-green",
      "primary": "#14834A",
      "brand": "#0F6B3B",
      "accent2": "#F0B24C",
      "background": "#0A150F",
      "card": "#122019",
      "foreground": "#EAF2E6",
      "radius": 18,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 20,
      "opacity": 66,
      "depth": 60,
      "glow": 62,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "zest-orange",
    "label": "Zest",
    "desc": "Freshly squeezed citrus energy",
    "category": "playful",
    "theme": {
      "preset": "zest-orange",
      "primary": "#CC4407",
      "brand": "#C7410A",
      "accent2": "#1DA84C",
      "background": "#FFF9F3",
      "card": "#FFFFFF",
      "foreground": "#2B1707",
      "radius": 20,
      "surface": "clay",
      "hero": "showcase",
      "bg": "rays",
      "font": "inter",
      "displayFont": "poppins",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 45,
      "glow": 15,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "majestic-wine",
    "label": "Majestic Wine",
    "desc": "Opulent wine, refined gold",
    "category": "luxury",
    "theme": {
      "preset": "majestic-wine",
      "primary": "#A02142",
      "brand": "#8C1D3C",
      "accent2": "#C9A24B",
      "background": "#180810",
      "card": "#251019",
      "foreground": "#F3E8D5",
      "radius": 10,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "gradient",
      "font": "inter",
      "displayFont": "playfair",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 45,
      "dark": true,
      "gradientButtons": true,
      "hover3d": false,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "scarlet-opera",
    "label": "Scarlet Opera",
    "desc": "Theatrical scarlet on velvet black",
    "category": "luxury",
    "theme": {
      "preset": "scarlet-opera",
      "primary": "#DA1D36",
      "brand": "#B4122C",
      "accent2": "#C9A24E",
      "background": "#0D0507",
      "card": "#1A0A0D",
      "foreground": "#F6E9E5",
      "radius": 14,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "rays",
      "font": "jakarta",
      "displayFont": "playfair",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 55,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "night-arcade",
    "label": "Night Arcade",
    "desc": "Neon synthwave arcade glow",
    "category": "dark",
    "theme": {
      "preset": "night-arcade",
      "primary": "#7C3AED",
      "brand": "#DB2777",
      "accent2": "#22D3EE",
      "background": "#0B0614",
      "card": "#171029",
      "foreground": "#F4F1FF",
      "radius": 16,
      "surface": "glass",
      "hero": "spotlight",
      "bg": "aurora",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1.02,
      "blur": 20,
      "opacity": 62,
      "depth": 60,
      "glow": 74,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "volcanic-ash",
    "label": "Volcanic Ash",
    "desc": "Molten glow on rugged charcoal",
    "category": "dark",
    "theme": {
      "preset": "volcanic-ash",
      "primary": "#CD450E",
      "brand": "#C8410B",
      "accent2": "#F5A524",
      "background": "#14100E",
      "card": "#211C18",
      "foreground": "#F5EFE9",
      "radius": 10,
      "surface": "elevated",
      "hero": "spotlight",
      "bg": "mesh",
      "font": "inter",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 60,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "cherry-cola",
    "label": "Cherry Cola",
    "desc": "Retro fizz, diner nostalgia",
    "category": "vibrant",
    "theme": {
      "preset": "cherry-cola",
      "primary": "#D62A3D",
      "brand": "#DA304A",
      "accent2": "#E9B44C",
      "background": "#201210",
      "card": "#2E1815",
      "foreground": "#F6E7D6",
      "radius": 16,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "rays",
      "font": "poppins",
      "displayFont": "montserrat",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 45,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  },
  {
    "key": "cyber-lime",
    "label": "Cyber Lime",
    "desc": "Acid lime, jet-black voltage",
    "category": "dark",
    "theme": {
      "preset": "cyber-lime",
      "primary": "#517C00",
      "brand": "#4C7A00",
      "accent2": "#C8FF33",
      "background": "#0A0C07",
      "card": "#14180D",
      "foreground": "#F2F6E9",
      "radius": 14,
      "surface": "glossy",
      "hero": "spotlight",
      "bg": "grid",
      "font": "inter",
      "displayFont": "space",
      "fontScale": 1,
      "blur": 0,
      "opacity": 100,
      "depth": 70,
      "glow": 72,
      "dark": true,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": false
    }
  },
  {
    "key": "tangerine-pop",
    "label": "Tangerine Pop",
    "desc": "Bouncy tangerine on crisp white",
    "category": "playful",
    "theme": {
      "preset": "tangerine-pop",
      "primary": "#C2410C",
      "brand": "#CE450A",
      "accent2": "#FFB703",
      "background": "#FFF7EE",
      "card": "#FFFFFF",
      "foreground": "#2A1810",
      "radius": 24,
      "surface": "clay",
      "hero": "showcase",
      "bg": "dots",
      "font": "jakarta",
      "displayFont": "poppins",
      "fontScale": 1.02,
      "blur": 0,
      "opacity": 100,
      "depth": 60,
      "glow": 22,
      "dark": false,
      "gradientButtons": true,
      "hover3d": true,
      "animations": true,
      "pill": true
    }
  }
];
