import type { Homepage, Settings } from "@/lib/types";
export { THEME_PRESETS, defaultTheme } from "@/lib/theme-presets";

export const defaultSettings: Settings = {
  storeName: "Banglarfish",
  storeEmail: "support@banglarfish.com",
  storePhone: "+880 9642-057407",
  currency: "BDT",
  currencySymbol: "৳",
  currencyPosition: "before",
  currencyDecimals: 0,
  currencyThousandSep: ",",
  address: "House-349, Road-15, Block-K, South Banasree, Dhaka",
  freeShippingThreshold: 2000,
  standardShipping: 80,
  taxPercent: 0,
  cod: true,
  bkash: true,
  nagad: true,
  sslcommerz: false,
  facebook: "https://facebook.com/banglarfish",
  instagram: "https://instagram.com/banglarfish",
  youtube: "https://youtube.com/@banglarfish",
  metaTitle: "Banglarfish — Fresh Fish Delivered from River to Kitchen",
  metaDescription: "Order fresh hilsa, rohu, prawn, and dried fish online in Bangladesh. Same-day delivery in Dhaka.",
  announcement: "Free delivery on orders over ৳2,000 · Same-day delivery in Dhaka",
};

export const defaultHomepage: Homepage = {
  heroEyebrow: "Fresh Catch · Delivered Daily",
  heroTitleTop: "From the river",
  heroTitleBottom: "to your kitchen",
  heroSubtitle:
    "Premium hilsa, freshwater fish, prawns and shutki — sourced directly from Bangladeshi fishermen, cleaned, iced, and delivered same-day.",
  heroCtaPrimary: { label: "Shop Now", href: "/shop" },
  heroCtaSecondary: { label: "Explore Hilsa", href: "/category/hilsa" },
  heroImage: "/img/hero-fish.jpg",
  stats: [
    { n: "10K+", label: "Happy Customers" },
    { n: "50+", label: "Fish Varieties" },
    { n: "24hr", label: "Fresh Delivery" },
  ],
  features: [
    { icon: "truck", title: "Same-Day Delivery", desc: "Order by 11 AM in Dhaka" },
    { icon: "snowflake", title: "Iced & Fresh", desc: "Cold-chain to your door" },
    { icon: "shield", title: "100% Guarantee", desc: "Freshness or refund" },
    { icon: "clock", title: "Cash on Delivery", desc: "Pay when it arrives" },
  ],
  categoriesEyebrow: "Shop by Category",
  categoriesTitle: "Find your favorite catch",
  bestSellersEyebrow: "Best Sellers",
  bestSellersTitle: "What our customers love",
  promos: [
    { title: "Padma Hilsa Season", subtitle: "Save up to 20%", href: "/category/hilsa", theme: "primary" },
    { title: "Jumbo Prawns", subtitle: "Fresh from Bay of Bengal", href: "/category/prawn-shrimp", theme: "brand" },
  ],
  newArrivalsEyebrow: "Just In",
  newArrivalsTitle: "New arrivals",
  testimonialsEyebrow: "Reviews",
  testimonialsTitle: "Loved by home cooks & chefs",
  testimonials: [
    { n: "Ayesha R.", loc: "Gulshan, Dhaka", t: "The hilsa was as fresh as if I bought it at the ghat. Perfectly cleaned too — huge time saver." },
    { n: "Rafiq H.", loc: "Uttara, Dhaka", t: "Golda chingri quality was excellent. Fast delivery, well-iced, and the app is very easy to use." },
    { n: "Nusrat J.", loc: "Chattogram", t: "Finally a place to get authentic Padma ilish outside Dhaka. Will keep ordering." },
  ],
  newsletterTitle: "Get 10% off your first order",
  newsletterSubtitle: "Sign up for weekly catch updates and exclusive deals.",
  newsletterCta: "Subscribe",
  recipesEyebrow: "From our kitchen",
  recipesTitle: "Fish recipes to try tonight",
  blogEyebrow: "Journal",
  blogTitle: "Guides, stories & sourcing",
  masalaEyebrow: "Pantry",
  masalaTitle: "Fish masala & spice blends",
  masalaCategory: "fish-masala",
  sections: {
    categories: true,
    howItWorks: true,
    bestSellers: true,
    masala: true,
    promos: true,
    newArrivals: true,
    recipes: true,
    blog: true,
    testimonials: true,
    newsletter: true,
    comments: true,
    contact: true,
  },
};
