/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCodeRouteImport } from './routes/admin.code'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminContentTypesRouteImport } from './routes/admin.content-types'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomerGroupsRouteImport } from './routes/admin.customer-groups'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminDocsRouteImport } from './routes/admin.docs'
import { Route as AdminEmailRouteImport } from './routes/admin.email'
import { Route as AdminGiftcardsRouteImport } from './routes/admin.giftcards'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminHomepageTemplatesRouteImport } from './routes/admin.homepage-templates'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminLandingRouteImport } from './routes/admin.landing'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminMailRouteImport } from './routes/admin.mail'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPluginsRouteImport } from './routes/admin.plugins'
import { Route as AdminPrivacyRouteImport } from './routes/admin.privacy'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminRecipesRouteImport } from './routes/admin.recipes'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSocialRouteImport } from './routes/admin.social'
import { Route as AdminStarterRouteImport } from './routes/admin.starter'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminTaxRouteImport } from './routes/admin.tax'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CTypeRouteImport } from './routes/c.$type'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as InvoiceOrderNumberRouteImport } from './routes/invoice.$orderNumber'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminContentTypeRouteImport } from './routes/admin.content.$type'
import { Route as CTypeIndexRouteImport } from './routes/c.$type.index'
import { Route as CTypeSlugRouteImport } from './routes/c.$type.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodeRoute = AdminCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypesRoute = AdminContentTypesRouteImport.update({
  id: '/content-types',
  path: '/content-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerGroupsRoute = AdminCustomerGroupsRouteImport.update({
  id: '/customer-groups',
  path: '/customer-groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftcardsRoute = AdminGiftcardsRouteImport.update({
  id: '/giftcards',
  path: '/giftcards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageTemplatesRoute = AdminHomepageTemplatesRouteImport.update({
  id: '/homepage-templates',
  path: '/homepage-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginsRoute = AdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrivacyRoute = AdminPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStarterRoute = AdminStarterRouteImport.update({
  id: '/starter',
  path: '/starter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxRoute = AdminTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CTypeRoute = CTypeRouteImport.update({
  id: '/c/$type',
  path: '/c/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceOrderNumberRoute = InvoiceOrderNumberRouteImport.update({
  id: '/invoice/$orderNumber',
  path: '/invoice/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentTypeRoute = AdminContentTypeRouteImport.update({
  id: '/content/$type',
  path: '/content/$type',
  getParentRoute: () => AdminRoute,
} as any)
const CTypeIndexRoute = CTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CTypeRoute,
} as any)
const CTypeSlugRoute = CTypeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/code': typeof AdminCodeRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content-types': typeof AdminContentTypesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/giftcards': typeof AdminGiftcardsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-templates': typeof AdminHomepageTemplatesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/starter': typeof AdminStarterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tax': typeof AdminTaxRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$type': typeof CTypeRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/l/$slug': typeof LSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/content/$type': typeof AdminContentTypeRoute
  '/c/$type/$slug': typeof CTypeSlugRoute
  '/c/$type/': typeof CTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/code': typeof AdminCodeRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content-types': typeof AdminContentTypesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/giftcards': typeof AdminGiftcardsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-templates': typeof AdminHomepageTemplatesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/starter': typeof AdminStarterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tax': typeof AdminTaxRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/l/$slug': typeof LSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/content/$type': typeof AdminContentTypeRoute
  '/c/$type/$slug': typeof CTypeSlugRoute
  '/c/$type': typeof CTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/code': typeof AdminCodeRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/content-types': typeof AdminContentTypesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/giftcards': typeof AdminGiftcardsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-templates': typeof AdminHomepageTemplatesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/starter': typeof AdminStarterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tax': typeof AdminTaxRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$type': typeof CTypeRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/invoice/$orderNumber': typeof InvoiceOrderNumberRoute
  '/l/$slug': typeof LSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/content/$type': typeof AdminContentTypeRoute
  '/c/$type/$slug': typeof CTypeSlugRoute
  '/c/$type/': typeof CTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/complete-profile'
    | '/contact'
    | '/order-confirmed'
    | '/preferences'
    | '/recipes'
    | '/reset-password'
    | '/shop'
    | '/unsubscribe'
    | '/account'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/code'
    | '/admin/comments'
    | '/admin/contact'
    | '/admin/content-types'
    | '/admin/coupons'
    | '/admin/customer-groups'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/giftcards'
    | '/admin/health'
    | '/admin/homepage'
    | '/admin/homepage-templates'
    | '/admin/jobs'
    | '/admin/landing'
    | '/admin/languages'
    | '/admin/mail'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/modules'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/plugins'
    | '/admin/privacy'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/recipes'
    | '/admin/redirects'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shipping'
    | '/admin/sms'
    | '/admin/social'
    | '/admin/starter'
    | '/admin/subscribers'
    | '/admin/tax'
    | '/admin/theme'
    | '/admin/visitors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/c/$type'
    | '/category/$slug'
    | '/invoice/$orderNumber'
    | '/l/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/content/$type'
    | '/c/$type/$slug'
    | '/c/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/complete-profile'
    | '/contact'
    | '/order-confirmed'
    | '/preferences'
    | '/recipes'
    | '/reset-password'
    | '/shop'
    | '/unsubscribe'
    | '/account'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/code'
    | '/admin/comments'
    | '/admin/contact'
    | '/admin/content-types'
    | '/admin/coupons'
    | '/admin/customer-groups'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/giftcards'
    | '/admin/health'
    | '/admin/homepage'
    | '/admin/homepage-templates'
    | '/admin/jobs'
    | '/admin/landing'
    | '/admin/languages'
    | '/admin/mail'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/modules'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/plugins'
    | '/admin/privacy'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/recipes'
    | '/admin/redirects'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shipping'
    | '/admin/sms'
    | '/admin/social'
    | '/admin/starter'
    | '/admin/subscribers'
    | '/admin/tax'
    | '/admin/theme'
    | '/admin/visitors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/category/$slug'
    | '/invoice/$orderNumber'
    | '/l/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin'
    | '/blog'
    | '/admin/content/$type'
    | '/c/$type/$slug'
    | '/c/$type'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/complete-profile'
    | '/contact'
    | '/order-confirmed'
    | '/preferences'
    | '/recipes'
    | '/reset-password'
    | '/shop'
    | '/unsubscribe'
    | '/_authenticated/account'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/branding'
    | '/admin/categories'
    | '/admin/code'
    | '/admin/comments'
    | '/admin/contact'
    | '/admin/content-types'
    | '/admin/coupons'
    | '/admin/customer-groups'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/docs'
    | '/admin/email'
    | '/admin/giftcards'
    | '/admin/health'
    | '/admin/homepage'
    | '/admin/homepage-templates'
    | '/admin/jobs'
    | '/admin/landing'
    | '/admin/languages'
    | '/admin/mail'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/modules'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/plugins'
    | '/admin/privacy'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/recipes'
    | '/admin/redirects'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shipping'
    | '/admin/sms'
    | '/admin/social'
    | '/admin/starter'
    | '/admin/subscribers'
    | '/admin/tax'
    | '/admin/theme'
    | '/admin/visitors'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/c/$type'
    | '/category/$slug'
    | '/invoice/$orderNumber'
    | '/l/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/content/$type'
    | '/c/$type/$slug'
    | '/c/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ContactRoute: typeof ContactRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PreferencesRoute: typeof PreferencesRoute
  RecipesRoute: typeof RecipesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CTypeRoute: typeof CTypeRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  InvoiceOrderNumberRoute: typeof InvoiceOrderNumberRoute
  LSlugRoute: typeof LSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/code': {
      id: '/admin/code'
      path: '/code'
      fullPath: '/admin/code'
      preLoaderRoute: typeof AdminCodeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-types': {
      id: '/admin/content-types'
      path: '/content-types'
      fullPath: '/admin/content-types'
      preLoaderRoute: typeof AdminContentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-groups': {
      id: '/admin/customer-groups'
      path: '/customer-groups'
      fullPath: '/admin/customer-groups'
      preLoaderRoute: typeof AdminCustomerGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/giftcards': {
      id: '/admin/giftcards'
      path: '/giftcards'
      fullPath: '/admin/giftcards'
      preLoaderRoute: typeof AdminGiftcardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage-templates': {
      id: '/admin/homepage-templates'
      path: '/homepage-templates'
      fullPath: '/admin/homepage-templates'
      preLoaderRoute: typeof AdminHomepageTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail': {
      id: '/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugins': {
      id: '/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AdminPluginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/privacy': {
      id: '/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AdminPrivacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/starter': {
      id: '/admin/starter'
      path: '/starter'
      fullPath: '/admin/starter'
      preLoaderRoute: typeof AdminStarterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tax': {
      id: '/admin/tax'
      path: '/tax'
      fullPath: '/admin/tax'
      preLoaderRoute: typeof AdminTaxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/c/$type': {
      id: '/c/$type'
      path: '/c/$type'
      fullPath: '/c/$type'
      preLoaderRoute: typeof CTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$orderNumber': {
      id: '/invoice/$orderNumber'
      path: '/invoice/$orderNumber'
      fullPath: '/invoice/$orderNumber'
      preLoaderRoute: typeof InvoiceOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$type': {
      id: '/admin/content/$type'
      path: '/content/$type'
      fullPath: '/admin/content/$type'
      preLoaderRoute: typeof AdminContentTypeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/c/$type/': {
      id: '/c/$type/'
      path: '/'
      fullPath: '/c/$type/'
      preLoaderRoute: typeof CTypeIndexRouteImport
      parentRoute: typeof CTypeRoute
    }
    '/c/$type/$slug': {
      id: '/c/$type/$slug'
      path: '/$slug'
      fullPath: '/c/$type/$slug'
      preLoaderRoute: typeof CTypeSlugRouteImport
      parentRoute: typeof CTypeRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCodeRoute: typeof AdminCodeRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminContentTypesRoute: typeof AdminContentTypesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomerGroupsRoute: typeof AdminCustomerGroupsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminGiftcardsRoute: typeof AdminGiftcardsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminHomepageTemplatesRoute: typeof AdminHomepageTemplatesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPluginsRoute: typeof AdminPluginsRoute
  AdminPrivacyRoute: typeof AdminPrivacyRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminStarterRoute: typeof AdminStarterRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTaxRoute: typeof AdminTaxRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentTypeRoute: typeof AdminContentTypeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCodeRoute: AdminCodeRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminContentTypesRoute: AdminContentTypesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomerGroupsRoute: AdminCustomerGroupsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminGiftcardsRoute: AdminGiftcardsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminHomepageTemplatesRoute: AdminHomepageTemplatesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminMailRoute: AdminMailRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPluginsRoute: AdminPluginsRoute,
  AdminPrivacyRoute: AdminPrivacyRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetRoute: AdminResetRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminStarterRoute: AdminStarterRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTaxRoute: AdminTaxRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentTypeRoute: AdminContentTypeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CTypeRouteChildren {
  CTypeSlugRoute: typeof CTypeSlugRoute
  CTypeIndexRoute: typeof CTypeIndexRoute
}

const CTypeRouteChildren: CTypeRouteChildren = {
  CTypeSlugRoute: CTypeSlugRoute,
  CTypeIndexRoute: CTypeIndexRoute,
}

const CTypeRouteWithChildren = CTypeRoute._addFileChildren(CTypeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ContactRoute: ContactRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PreferencesRoute: PreferencesRoute,
  RecipesRoute: RecipesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CTypeRoute: CTypeRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  InvoiceOrderNumberRoute: InvoiceOrderNumberRoute,
  LSlugRoute: LSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
